### ISSUE TITLE
RFC: Row identities in MJ schema

### ISSUE THREAD

**Issue by cadam11** [MemberJunction/MJ#385]
# Problem description

While MJ is built on a single CDP that includes data from many external sources, it relies on an administrative schema (defaulting to `__mj`, although it may be customized per installation) for managing its own state. The schema has tables for many internal entities, including the Entity table itself. As users set up their own MJ installation and make stateful changes (running CodeGen, creating views, adding favorites, or almost any other action in MJ) new records are created within the internal `__mj` tables as needed.

Our current strategy for managing database schema changes uses Redgate to identify and creates migration scripts based on both structure as well as data. The latter is important since the system configuration is largely expressed through data in the `__mj` tables. These tables generally use an autoincrementing numerical `ID` column for row identities.

New rows created for _system_ purposes are often created with the next ID in the base sequence, while new rows created through user interactions generally have IDs beginning at a predetermined, high threshold (>=2500000) intended to avoid ID collisions. Despite this, there remains the potential (and there have been cases) of identity conflicts when upgrading MJ databases.

Our goal is to seek a solution that can manage or avoid having _system_ records within the `__mj` schema collide with records added through user interaction.

# Design constraints and considerations

- The MJ database is currently only an MS SQL server, so compatibility/performance on that would be preferable
- Sortable IDs are a nice-to-have

# Proposed solutions

The general expectation is that any meaningful change to the row identities within the `__mj` is a major change and users will likely have to re-setup their CDP databases.

1. Use [KSUID](https://github.com/segmentio/ksuid)s for row identities
  - These 27-character identifiers offer uniqueness without managing address spaces, are portable base-62 strings, and allow binary sorting to preserve order even in a distributed system
2. Use [ULID](https://github.com/ulid/spec)
 - The advantage of this spec is that there's an [SQL server implementation](https://github.com/rmalayter/ulid-mssql) 

> [!NOTE]
> More may be added once the problem is adequately understood and expressed

# Selected solution

> [!NOTE]
> Pending community comments

# Implementation

1. Remove the current ID columns in all `__mj` tables
1. Replace them with a column defined as ID that is a KSUID type.
1. Add a SQL Server function to generate the identifier so that we can encapsulate this complexity for use in the `spCreate` procedure for each entity in the system
1. Make this type of primary key a first-class supported approach for entities as an alternative to IDENTITY column-based primary keys so that application developers who want portability for their metadata (as well as users of MJ) can utilize this approach for their ID values

**Comment by cadam11** [comment]
@AN-BC RFC as discussed. Please feel free to revise as needed

**Comment by AN-BC** [comment]
My current thinking would be that we:

1. Remove the current ID columns in all __mj tables
2. Replace them with a column defined as ID that is a KSUID type.
3. Ideally, we generate the KSUID as a SQL Server `function` so that we can embed this complexity in the spCreate procedure for each entity in the system
4. Make this type of primary key a first-class supported approach for entities as an alternative to IDENTITY column based primary keys so that application developers who want portability for their metadata (as well as users of MJ) can utilize this approach for their ID values
5. The only question I have is how this affects the user experience if the KSUID based ID field replaces the INT identity and therefore for anything user facing if there is a need for an ID value, it will be much harder to use. But perhaps there isn't a need for this?

**Comment by AN-BC** [comment]
@hiltongr @dray-mc  would be great to have both of your comments on this when time permits

**Comment by cadam11** [comment]
This was implemented in major version 2.0.0
