### ISSUE TITLE
Support for soft deleting records

### ISSUE THREAD

**Issue by cadam11** [MemberJunction/MJ#390]
TBD @AN-BC 

Maybe enabling soft deletes on an Entity is a pre-requisite for merging records / dedup.

**Comment by AN-BC** [comment]
- Metadata additions:
- Entities: DeleteType: Hard or Soft - when set to Hard, will work as it currently does. When set to Soft - the following will occur:
1. `CodeGen` will auto add `__mj_DeleteAt` column to the entity in question
2. The generated base view will filter **out** any record that has any value in the __mj_DeletedAt column, ensuring the records appear deleted
3. `CodeGen` will generate the `spDelete` procedure to update a record with a GETUTCTIME() instead of the hard delete which actually deletes the rows from the table.
4. CodeGen will ensure that the `__mj_DeletedAt` column is never updated by an spUpdate/spCreate proc given its special meaning
- Entities; AllowRecordMerge will be added as a bit field and future Merge record support will require this field to be turned on. Additionally, merge support will require that DeleteType='Soft'

**Comment by AN-BC** [comment]
This was completed already
